- name: Update Web server
  hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
    - name: Install our packages
      ansible.builtin.apt:
        name: ['apache2']
        state: present
        update_cache: true
